### ISSUE TITLE
Heavy performance hit to rendering equations after Obsidian is running for a while

### ISSUE THREAD

**Issue by xieve** [RyotaUshio/obsidian-math-booster#186] opened 2023-11-03 11:40 UTC
After running and using Obsidian for a few minutes, each render of any equation progressively gets slower, to the point where I have to type in equations "blindly" because the entire application locks up for several seconds to tens of seconds. This issue does not occur when Math Booster is deactivated.
Here's a screenshot of a profiling run where I typed into an equation while this issue was occurring. I'm not sure about posting entire profiles publically, but maybe I could submit it privately somehow?
![image](https://github.com/RyotaUshio/obsidian-math-booster/assets/20223093/56c2cbbb-a9b4-4259-924a-e0d3b5803891)

Here's my debug info:
```
SYSTEM INFO:
	Obsidian version: v1.4.16
	Installer version: v1.4.16
	Operating system: Windows 10 Pro 10.0.19045
	Login status: not logged in
	Insider build toggle: off
	Live preview: on
	Legacy editor: off
	Base theme: light
	Community theme: none
	Snippets enabled: 1
	Restricted mode: off
	Plugins installed: 35
	Plugins enabled: 9
		1: Excalidraw v1.9.24
		2: Auto Link Title v1.4.1
		3: MathLinks v0.4.6
		4: Dataview v0.5.61
		5: Extended MathJax v0.4.1
		6: Advanced Tables v0.19.1
		7: Templater v1.16.4
		8: Commander v0.5.0
		9: Latex Suite v1.8.4
		10: Math Booster v1.0.4
```

**Comment by RyotaUshio** [comment] 2023-11-03 12:36
Hi, thanks for reporting. 

The current implementation of `informChange` (which is a part of MathLinks) is quite inefficient, and I suspect this is the cause of your problem. I'm planning to rewrite it to improve performance, and it might resolve the issue.

Sorry for the inconvenience, but please wait for the next release!

**Comment by RyotaUshio** [comment] 2023-11-06 19:27
@xieve Probably I will be able to have time to implement a partial fix to this. Could you send me the profile to ushio@ms.k.u-tokyo.ac.jp ?

**Comment by RyotaUshio** [comment] 2023-11-16 14:21
Hey @xieve, if you're interested, try the alpha release [2.0.0-alpha](https://github.com/RyotaUshio/obsidian-math-booster/releases/tag/2.0.0-alpha) and let me know how much it helped. Of course, there are still a lot of things I can do to improve performance; just a work in progress.

**Comment by RyotaUshio** [comment] 2023-11-24 12:55
Now version 2 is officially available from the community plugins browser in Obsidian. I think it's way more performant than version 1 and your problem will be resolved. I'm closing this issue, but feel free to open a new issue if you encounter a similar performance hit with version 2.

**Closed by RyotaUshio** 2023-11-24 12:55 UTC
